defaults:
  - _self_
  - clip/general

process_data_config:
  num_processes: 60
  num_shards: 30
  temp_dir_base_path: data
  shuffle_before_split: true
  split_ratios:
    train: 0.7
    val: 0.15
    test: 0.15
